DELETE http://localhost:3003/api/blogs/660588e7425dc83f29dba71a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbGxleGQiLCJpZCI6IjY2MDU4MGFlZTA0MmY5NjYzMzlmMWIyMyIsImlhdCI6MTcxMTYzODM5N30.UaCtP2DL6HqTodlj0y8JAM6dEWv_kSKovuP4z_TXYoo
