POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbGxleiIsImlkIjoiNjYwNTc0OTk2NjdkZGQ3OTYyNzBkZTFjIiwiaWF0IjoxNzExNjM1NDMwfQ.Ss0wpzj7f-3Hcq_yQS9dM8JH7obj_KOOqH_TBpprBNM

{
  "title": "blogi",
  "author": "kalle",
  "url": "google.com",
  "likes": 10
}